### ISSUE TITLE
Simplify setup process by auto correcting scene resource paths

### ISSUE THREAD

**Issue by valkyrienyanko** [ValksGodotTools/Template#18]
> [!NOTE]
> I have tried both `DirAccess.Rename()` and `File.Move()`. Neither update the resource references in the scene.

![Untitled](https://github.com/user-attachments/assets/00d39bbc-aa89-4222-9c63-1cbcdd14ffc6)

> [!NOTE]
> This is how assets are currently being moved around.

https://github.com/ValksGodotTools/Template/blob/8ee9c10cf9027f813b2371bbcfcabcd5841c5a25/0%20Setup/Setup.cs#L146-L155

> [!NOTE]
> I have created an issue about this on the Godot repo https://github.com/godotengine/godot/issues/95960

**Comment by valkyrienyanko** [comment]
This is actually a big deal because not just the main scene but all scenes become broken and you need to manually click fix dependencies on each scene.

Perhaps the genres should not be moved around ever. I have not tested this yet but if it's easy to just mass drag files to the root and everything merges flawlessly then maybe this is how it should be done.

Why is it that manually dragging files in the Godot editor keeps dependencies intact but moving files via script does not.

**Comment by Hilderin** [comment]
The reason why it's different when you move a script in the editor versus directly on disk is that the editor knows both the source path and the destination path, allowing it to update some internal references. When moving files on disk, the editor only knows that a new file was created and an old file was deleted. There's probably a similar problem if you're using an external editor and move scripts around.

Check the answer here: https://github.com/godotengine/godot/issues/95960#issuecomment-2305406808

The way I see it, there are two ways this could be fixed:
1. Expose the method that moves the file to GDScript/C#, so internal references can be managed like in the FileSystem Dock.
2. Create a FileSystemWatcher that could detect file movements to obtain the source and destination paths. This is trivial in .NET, but in C++ and cross-platform, it seems to be much more difficult.

**Comment by valkyrienyanko** [comment]
> Expose the method that moves the file to GDScript/C#

How would I do that? I'm not sure what you mean by this.

> Create a FileSystemWatcher that could detect file movements to obtain the source and destination paths

Does this mean I have to manually change these paths in the scene (.tscn) file?

**Comment by Hilderin** [comment]
My bad, I found your issue from a link in an Godot repo issue, I tought I was still in Godot repo. Short of the engine exposing some methods i don't think it's fisable in GDScript, C# and even in a GDExtension right now. There's an issue in Godot to manage correctly file movement: https://github.com/godotengine/godot/issues/85274

**Comment by valkyrienyanko** [comment]
I have created a function to fix all resource paths in all scene files.
https://github.com/godotengine/godot/issues/95960#issuecomment-2316707097

I will be implementing this function very shortly.

**Comment by valkyrienyanko** [comment]
Closed due to the implementation of https://github.com/godotengine/godot/issues/95960#issuecomment-2316707097 across several messy commits.
